services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=taskdb
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend_db_init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: flask-backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=taskdb
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
    ports:
      - 5000:5000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_HOST=localhost
        - VITE_BACKEND_PORT=5000
    container_name: react-frontend
    ports:
      - 4173:4173
    depends_on:
      - backend

volumes:
  pg_data:
